# Generated by Django 5.1.5 on 2025-01-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_friends_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_video_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
