# Generated by Django 5.1.5 on 2025-01-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_room_room_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_video_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
