# Generated by Django 5.1.5 on 2025-01-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_friend_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
