# Generated by Django 5.1.5 on 2025-01-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_friend_friend_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_banned',
            field=models.JSONField(null=True),
        ),
    ]
