# Generated by Django 5.1.5 on 2025-01-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_room_room_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_banned',
        ),
    ]
